const darkmode_styles = {
    header_style: {
        display: "flex",
        height: "7vh",
        width: "100%",
        backgroundColor: "black",
        justifyContent: "space-detween",
        alignItems: "center",
        position: "fixed",
        top: "0",
        zIndex: "10",
    },
    h1 : {
        color: "white",
        fontWeight: "900",
        fontStyle: "cursive",
        width: "90%",
        paddingLeft: "10%"
    },
    searchinput_style : {
        marginRight: "4%",
        marginLeft: "2%",
        width: "95%",
        height: '1.6rem',
        border: 'none',
        outline: 'none',
        color: 'white',
        fontWeight: 'bold',
        borderBottom: '1px solid #fff',
        backgroundColor: "black",
    },
    searchactionbtn_style : {
        backgroundColor : "black",
        border: "none",
    },
    showsearchformbtn_style : {
        backgroundColor : "black",
        border : "none",
        display : "block",
    },
    showmenubtn_style : {
        backgroundColor : "black",
        border : "none",
        display : "block",
    },
    maincontainer_style : {
        backgroundColor: "rgb(61, 56, 56)",
        overflowY: "scroll",
        marginTop: "7vh"
    },
    searchfill : "white",
    suggestioncontainer_style : { backgroundColor: "rgb(61, 56, 56)"   },

    viewimg_container : { backgroundColor: "#373737"},
     arttitlecontainer_style : {
        margin: "0",
        borderBottom: "1px solid gray",
    },
    arttitlepara_style : {
        margin: "0",
        fontFamily: "cursive",
        marginLeft: "2%",
        fontWeight: "900",
        textAlign: "center",
        color: "aliceblue",
    },
    commentcancle_parastyle : {
        paddingLeft: "5%",
        textTransform: "Capitalize",
        color: "white",
    },
    pricepara_style : {
        paddingLeft: "5%",
        fontSize: ".9rem",
        fontWeight: "900",
        color: "yellow",
        width: "60%",
    },
    likecountpar_style : {
        fontSize: ".7rem",
        fontWeight: "900",
        margin: "0",
        alignSelf: "center",
        color: "white",
    },
    pricelikebtn_container : {
        display: "flex",
        justifyContent: "space-between",
        alignItems: "center",
        height: "7vh",
        margin: "0 auto",
        borderBottom: "1px solid rgb(85, 85, 85)",
        
    },
    accountpar_style : {
        marginLeft: "5.5%",
        marginTop: "4.7%",
        fontSize: ".8rem",
        textDecoration: "underline",
        color: "white",
    },
    commentbtns_container : {
        borderBottom: "1px solid" ,
        borderTop: "1px solid rgb(85, 85, 85)",
        marginTop: "1%",
        padding: "2% 3%",
        display: "flex",
    },
    commentsbtn_style : {
        backgroundColor: "rgba(0,0,0,0)",
        border: "none",
        textTransform: "Capitalize",
        fontSize: "1rem",
        width: "50%",
        paddingLeft: "2.5%",
        textAlign: "left",
        color:"white",
    },
    buybtn_style : {
        padding: "0rem 1.6rem",
        backgroundColor: "rgb(253, 218, 197)",
        color: "black",
        fontWeight: "700",
        textTransform: "uppercase",
        border: "none",
        height: "2.1rem",
        marginTop: ".5rem",
        marginRight: "1.3rem",
        opacity: "1",
    },
    commentform_container_style : {
        borderBottom: "1px solid rgb(85, 83, 83)",
        paddingBottom: "1.7rem",
    },
    commenttextarea_style : {
        width: "90%",
        marginLeft: "5%",
        border: "none",
        borderBottom:"1px solid gray",
        height: "3.3rem",
        paddingTop: "5%",
        outline: "none",
        color: "white",
        backgroundColor: "rgb(55, 55, 55)",
    },
    commentcancle_containerstyle : {
        display: "flex",
        justifyContent: "space-between",
        alignItems: "center",
        borderBottom: "1px solid rgb(85, 83, 83)",
    },
    commentcanclebtn_style : {
        backgroundColor: "inherit",
        fontSize: ".8rem",
        border: "none",
        textTransform: "uppercase",
        paddingTop: ".35rem",
        color: "white",
    },
    commentsubmitbtn_style : {
        backgroundColor: "inherit",
        fontSize: ".8rem",
        border: "none",
        color: "yellow",
        textTransform: "capitalize",
        paddingTop: ".35rem",
    },
    commentaccount_style : {
        fontSize: ".7rem",
        color: "darkgray",
        paddingLeft: "2%",
        paddingTop: "1%",
    },
    commenttext_style : {
        fontSize: ".8rem",
        paddingLeft: "5%",
        paddingRight: "3%",
        marginTop: ".3rem",
        paddingBottom: ".5rem",
        borderBottom: "1px solid  rgb(85, 83, 83)",
        color: "white",
    },


}

export default darkmode_styles